language: node_js
node_js:
  - "8"
  - "6"
cache:
  directories:
    - "node_modules"
script:
  - npm run ci
deploy:
  provider: npm
  email: marcus.mennemeier@actano.de
  api_key:
    secure: "PTNbhnhhzovrPl/i3Qc3jBKM/y4dkypbpJ8/sUuYbw8EM4gAlbGVA+JgVN3Syf+fy7jtYaudbu3mjNxqvBEnuC9gRxEPKplu1oMMnnxZe1q5vcPR50buwjG/bj63U+5dFYZajdxvWCkyH+FhMvuPMELbIEvhODzXSzGKFdwjmkssJKY+0YkwrzrPxMCqYOnggEqEYHl8j6G6nAKwmnIbZCQ+9zRvt3wtghvvkuOIp+zpLwXzxO0+rqD0UN0Zf+aH7jp3f87dWFaxtXkFd3vJK00rg9fWAmuib6vVSUOHKREWxCutl/6gmJhGXLR7iatocT3TiKnbffmap3xffGi6ERyCNYa0Vcr3Ma/snG7so/7xTl+KVpe00zaiyaJG8PRwRSmW3UPKDmVeUlgU6/jpKXFAyq+HKi6MJ7BM/2MqQAwNN+x3bqZtNa4idzwRMu5Egxl2qCuxSjY6dQ3cBAk3MVZeo+qf5O3YUraVw4B/5D1f5LKUt0LPPyUo9ZF2wxY3nTvARETti0zcj/AdI0N1Uh5cl+oc3GwRtZ4iJVMyfSVR4oL4/2OKrlFBh0Tfuzqoyt5KzNP1crWz58OeoFzlFbux60WjR8usvmyDDYryi3I/1Zw1rq4O/aHa36pble8g+tCxagiVLqBz0Sn5b7vrr9l22E8iiBMEtqzRqf8CiCc="
  on:
    tags: true
    repo: actano/borders-logging
