language: node_js
node_js:
  - "6"
  - "8"
cache:
  directories:
    - "node_modules"
script:
  - npm run prepublish
deploy:
  provider: npm
  email: marcus.mennemeier@actano.de
  api_key:
    secure: "JaQ76EYSW2jGKlTu3O+kgf3LHGM7DFNMYgZ7wrCNTU10Wnn7ZmIcsvytM0UCoO6Hyrw6o/N/1wCCbwpsJIBsR71jh/Q0wzLg6Xiagwb8sJcS3jVWTXq9uHIM83KbNZKIKJ4i/XKJH9QHVVRIqGawSGdj5HxW/gg9V4edhLf6GyLX1vT30WHJEbNWxjLTTqvWxong+aciVV1LuWQddQW6y0QavQULcJy1MFMzUFOAPpXbF0i0kaG0ZBl52XOGOQ/gBChkkyYP0cRUgKkYqJLtP0Jv4OKHaJrtJ6Pyhn/2aT+qlPsiksWedfdctTT1kMi7+XkDXQhjZ3nZixVWrCG0XtUGwriqFK6uKZbORS7z+FVNZXYwl+OGZuxJFLakpjAASXdx+n1+vWKKd3i95QhgAfuq1Z66H3WGpuh18rlWkidvqOV09aZHApp/BGACmhr2C6HMMAsYee5Shx742vraNyc+EP/ym7TzfAae+keazscZdkurP5rGJVGo8ujLObL0Zsohs02CBkhdtMplzM4dWWTRv4PNszM4cIN0i1c3gUo0F2Ggboq//gb+1BNyUiPKSmbAj23SyY46QJhCH8vRKgpHSnBPYCeLPW2J6hi28XNHk+hk6E5K70ST1u5shZ32x/wyy9F+qbMsWa9xgjo6yqLqjf5pJxSUpMeMFClH3oE="
  on:
    tags: true
    repo: actano/borders
